In [11]:
import sys
import glob   
import pickle
import pandas as pd
import numpy as np



from IPython.core.display import display,HTML
display(HTML("<style>.container { width:100% !important; }</style>"))  # to make the notebook use the entire width of the browser

In [ ]:





    ###### dict_plos_UT_list_references_used_prior*

    path = '../data/dict_plos_UT_list_references_used_prior*'   

    
    
    
    
    lista_files=sorted(glob.glob(path))

    dict_plos_UT_list_references_used_prior  = {}
    

    for filename in lista_files:
        now = datetime.now()
        print(f"{now}:     loading    {filename}")  
        with open(filename, 'rb') as f:
            aux_dict_plos_UT_list_references_used_prior = pickle.load(f)

      
        now = datetime.now()
        dict_len = len(aux_dict_plos_UT_list_references_used_prior)
        print(f"  {now}: done loading, len: {dict_len}")
       

        dict_plos_UT_list_references_used_prior.update(aux_dict_plos_UT_list_references_used_prior)
        del(aux_dict_plos_UT_list_references_used_prior)
        now = datetime.now()
        dict_len = len(dict_plos_UT_list_references_used_prior)
        print (f"  {now}: master dict updated, len: {dict_len}")

        
        
        
    with open('../data/master_dict_plos_UT_list_references_used_prior_ALL.pkl', 'wb') as handle:
                 pickle.dump(dict_plos_UT_list_references_used_prior, handle, protocol = 2)
    print ("written:",'../data/master_dict_plos_UT_list_references_used_prior_ALL.pkl',len(master_dict))   


    lista_all_authored_UTs = list(dict_plos_UT_list_references_used_prior.keys())
    print ("len lista_all_authored_UTs:", len(lista_all_authored_UTs))

In [2]:





    # try:   #### ojo!!!! this is just a partial dict (for testing the rest of the code), not the master, master
    #     filename = '../data/master_dict_plos_UT_list_references_used_prior1.pkl'
    #     dict_plos_UT_list_references_used_prior = pickle.load(open(filename, 'rb'))   
    #     print ("done loading", filename, len(dict_plos_UT_list_references_used_prior)) 
    # except:        
    #     print ("MISSING FILE! ", filename, "  FORCED EXIT.")
    #     #exit()







    try:

        list_paper_UT = pickle.load(open('../data/list_paper_UT.pkl', 'rb'))   
        print ("done loading  ../data/list_paper_UT.pkl") 
    except:        
        print ("MISSING FILE!  ../data/list_paper_UT.pkl           FORCED EXIT.")
      #  exit()






    try:

        plos_df_simple = pickle.load(open('../data/plos_df.pkl', 'rb'))   
        print ("done loading  ../data/plos_df.pkl") 
    except:        
        print ("MISSING FILE!  ../data/plos_df.pkl           FORCED EXIT.")
       # exit()








    try:

        filename = '../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl'
        dict_plos_UT_list_papers_authored_by_team = pickle.load(open(filename, 'rb'))   
        print ("done loading ", filename, len(dict_plos_UT_list_papers_authored_by_team)) 

    except:        
        print ("MISSING FILE!  ", filename, "        FORCED EXIT.")
        #exit()











    df_merged = pickle.load(open('../data/df_reference_cite_plos_merged_simplified_added_more_columns_no_self-cit_one_ref_per_sect_ONLY_ARTICLES.pkl', 'rb'))
    print ("done loading df_merged", df_merged.shape)

done loading ../data/master_dict_plos_UT_list_references_used_prior1.pkl 77852
done loading  ../data/list_paper_UT.pkl
done loading  ../data/plos_df.pkl
done loading  ../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl 158813
done loading df_merged (5787634, 25)

In [3]:

print ("\n adding team_expertise to pandas df  ..................")
list_expertise_papers= []
for paper_UT in list_paper_UT:
    list_expertise_papers.append(len(dict_plos_UT_list_papers_authored_by_team[paper_UT]))






plos_df_simple['team_expertise'] = list_expertise_papers






###### i merge dataframes
df_merged = pd.merge(df_merged,  plos_df_simple, on='paper_UT', how='left')

 adding team_expertise to pandas df  ..................

                paper_UT  team_expertise
487945   000202894800008             114
2035210  000207443600001             233
5785005  000207443600002              72
667449   000207443600003             118
3998015  000207443600004               9

In [12]:



###################################
########################################
###################################
########################################

def get_reclycle_ref_yes_no(row, dict_plos_UT_list_references_used_prior):
    
    flag_recycled_ref = np.nan
    
    paper_UT = row.paper_UT
    ref_UT = row.reference_UT
    
    flag_recycled_ref = 0
        
    try:
        dict_plos_UT_list_references_used_prior[paper_UT]
       
        if ref_UT in dict_plos_UT_list_references_used_prior[paper_UT]:   # that is the list of papers authored by the list of authors of paper_UT until the year before of the publication of paper_UT
            flag_recycled_ref = 1
    except KeyError: pass
    
    
            
    return flag_recycled_ref

###################################
########################################



############ i add the recycled_ref label to the plos_ref database:
print ("\n adding recycled_ref label to pandas df  ..................")
df_merged['recycled_ref'] = df_merged.apply (lambda row: get_reclycle_ref_yes_no(row, dict_plos_UT_list_references_used_prior),axis=1)

 adding recycled_ref label to pandas df  ..................

In [15]:
df_merged.recycled_ref.value_counts()

0    5083717
1     703917
Name: recycled_ref, dtype: int64

In [ ]:
# ####### i glue together the partial dictionary for previous publications of a given team (plos UT)
# path = '../data/dict_plos_UT_list_papers_authored_by_team_until_then_*'   
# lista_files=sorted(glob.glob(path))

# master_dict_plos_UT_list_papers_authored_by_team  = {}
# lista_all_authored_UTs=[]

# for filename in lista_files:
#     dict_plos_UT_list_papers_authored_by_team = pickle.load(open(filename, 'rb'))
#     lista_all_authored_UTs += list(dict_plos_UT_list_papers_authored_by_team.keys())
#     print ("done loading", filename, len(dict_plos_UT_list_papers_authored_by_team), len(lista_all_authored_UTs))

#     master_dict_plos_UT_list_papers_authored_by_team.update(dict_plos_UT_list_papers_authored_by_team)
# with open('../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl', 'wb') as handle:
#              pickle.dump(master_dict_plos_UT_list_papers_authored_by_team, handle, protocol = 2)
# print ("written:",'../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl',len(master_dict_plos_UT_list_papers_authored_by_team))

,occurence,reference_UT,reference_rank,regex_sect_index,cite_count,ref_pub_year,paper_cite_count,plos_pub_year,sect_char_pos,sect_char_total,...,rel_loc_in_sect,plos_field,isolated_citation,paper_UT,total_refs,categ_codes,self_citation,number_authors,plos_article_type,team_expertise
0,1,A1995QY75100004,1,0,60.0,1995.0,2,2013.0,139,4029,...,0.034500,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
1,2,A1995QY75100004,1,3,60.0,1995.0,2,2013.0,494,5398,...,0.091515,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
2,1,000263911400006,3,0,5.0,2009.0,2,2013.0,142,4029,...,0.035244,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
3,1,000289279600018,4,0,29.0,2011.0,2,2013.0,269,4029,...,0.066766,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
4,3,000289279600018,4,3,29.0,2011.0,2,2013.0,3844,5398,...,0.712116,['D RO MULTIDISCIPLINARY SCIENCES'],1,000324515600133,37,0 5,0,5,@ Article,86
5,1,000287717700023,5,0,19.0,2011.0,2,2013.0,1635,4029,...,0.405808,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
6,1,000257589600013,7,0,27.0,2008.0,2,2013.0,2177,4029,...,0.540333,['D RO MULTIDISCIPLINARY SCIENCES'],1,000324515600133,37,0 5,0,5,@ Article,86
7,2,000257589600013,7,3,27.0,2008.0,2,2013.0,2578,5398,...,0.477584,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
8,1,000246465200001,8,0,29.0,2007.0,2,2013.0,1638,4029,...,0.406552,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
9,3,000246465200001,8,3,29.0,2007.0,2,2013.0,2579,5398,...,0.477770,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
10,1,000266227800006,10,0,270.0,2009.0,2,2013.0,1755,4029,...,0.435592,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
11,3,000266227800006,10,3,270.0,2009.0,2,2013.0,2580,5398,...,0.477955,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
12,1,000220879700004,12,0,743.0,2004.0,2,2013.0,2635,4029,...,0.654008,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
13,1,000177105200006,17,0,916.0,2002.0,2,2013.0,2638,4029,...,0.654753,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
14,1,000182540700009,18,0,463.0,2003.0,2,2013.0,3069,4029,...,0.761727,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
15,1,000227197300045,22,0,3116.0,2005.0,2,2013.0,3072,4029,...,0.762472,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
16,1,000290020400009,24,0,180.0,2011.0,2,2013.0,3368,4029,...,0.835939,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
17,2,000290020400009,24,3,180.0,2011.0,2,2013.0,2190,5398,...,0.405706,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
18,1,A1994NV95600001,26,0,113.0,1994.0,2,2013.0,3371,4029,...,0.836684,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
19,2,A1994NV95600001,26,3,113.0,1994.0,2,2013.0,2193,5398,...,0.406262,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
20,1,000256313500005,27,0,9.0,2008.0,2,2013.0,3780,4029,...,0.938198,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
21,1,000293136200014,28,0,16.0,2011.0,2,2013.0,3781,4029,...,0.938446,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
22,1,000174597100019,29,1,56.0,2002.0,2,2013.0,1217,5961,...,0.204160,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
23,1,000288797100011,30,2,71.0,2011.0,2,2013.0,3745,6345,...,0.590229,['D RO MULTIDISCIPLINARY SCIENCES'],1,000324515600133,37,0 5,0,5,@ Article,86
24,1,000179315000003,31,2,23.0,2002.0,2,2013.0,5830,6345,...,0.918834,['D RO MULTIDISCIPLINARY SCIENCES'],1,000324515600133,37,0 5,0,5,@ Article,86
25,2,000179315000003,31,3,23.0,2002.0,2,2013.0,3233,5398,...,0.598926,['D RO MULTIDISCIPLINARY SCIENCES'],1,000324515600133,37,0 5,0,5,@ Article,86
26,1,000276742200012,32,3,31.0,2010.0,2,2013.0,298,5398,...,0.055206,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
27,1,000275109000015,34,3,40.0,2010.0,2,2013.0,301,5398,...,0.055761,['D RO MULTIDISCIPLINARY SCIENCES'],0,000324515600133,37,0 5,0,5,@ Article,86
28,1,000282273900001,35,3,54.0,2010.0,2,2013.0,2290,5398,...,0.424231,['D RO MULTIDISCIPLINARY SCIENCES'],1,000324515600133,37,0 5,0,5,@ Article,86
29,1,000301067700008,36,3,9.0,2012.0,2,2013.0,3991,5398,...,0.739348,['D RO MULTIDISCIPLINARY SCIENCES'],1,000324515600133,37,0 5,0,5,@ Article,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1,000324379600006,38,3,14.0,2013.0,2,2015.0,5342,6003,...,0.889888,['D RO MULTIDISCIPLINARY SCIENCES'],0,000352084800063,41,0 5 8,0,9,@ Article,542
71,1,000252163400005,39,3,86.0,2008.0,2,2015.0,5343,6003,...,0.890055,['D RO MULTIDISCIPLINARY SCIENCES'],0,000352084800063,41,0 5 8,0,9,@ Article,542
72,1,000311838300021,40,3,10.0,2012.0,2,2015.0,5668,6003,...,0.944195,['D RO MULTIDISCIPLINARY SCIENCES'],0,000352084800063,41,0 5 8,0,9,@ Article,542
73,1,000329113500009,41,3,17.0,2014.0,2,2015.0,5669,6003,...,0.944361,['D RO MULTIDISCIPLINARY SCIENCES'],0,000352084800063,41,0 5 8,0,9,@ Article,542
74,1,000313346100007,2,0,6.0,2013.0,1,2015.0,591,2474,...,0.238884,['D RO MULTIDISCIPLINARY SCIENCES'],1,000358595900105,17,0 5 8,0,11,@ Article,1221
75,1,000337919300011,3,0,13.0,2014.0,1,2015.0,765,2474,...,0.309216,['D RO MULTIDISCIPLINARY SCIENCES'],1,000358595900105,17,0 5 8,0,11,@ Article,1221
76,1,000336485100015,4,0,35.0,2014.0,1,2015.0,1003,2474,...,0.405416,['D RO MULTIDISCIPLINARY SCIENCES'],0,000358595900105,17,0 5 8,0,11,@ Article,1221
77,3,000336485100015,4,3,35.0,2014.0,1,2015.0,2641,3514,...,0.751565,['D RO MULTIDISCIPLINARY SCIENCES'],0,000358595900105,17,0 5 8,0,11,@ Article,1221
78,1,000317992900007,5,0,48.0,2013.0,1,2015.0,1004,2474,...,0.405821,['D RO MULTIDISCIPLINARY SCIENCES'],0,000358595900105,17,0 5 8,0,11,@ Article,1221
79,3,000317992900007,5,3,48.0,2013.0,1,2015.0,2642,3514,...,0.751850,['D RO MULTIDISCIPLINARY SCIENCES'],0,000358595900105,17,0 5 8,0,11,@ Article,1221
80,1,000302075000006,7,0,51.0,2012.0,1,2015.0,1006,2474,...,0.406629,['D RO MULTIDISCIPLINARY SCIENCES'],0,000358595900105,17,0 5 8,0,11,@ Article,1221
81,1,000088727800022,13,1,181.0,2000.0,1,2015.0,3867,6117,...,0.632173,['D RO MULTIDISCIPLINARY SCIENCES'],1,000358595900105,17,0 5 8,0,11,@ Article,1221
82,1,A1987J391400011,15,1,5435.0,1987.0,1,2015.0,5404,6117,...,0.883440,['D RO MULTIDISCIPLINARY SCIENCES'],1,000358595900105,17,0 5 8,0,11,@ Article,1221
83,1,000285224500030,16,3,25.0,2010.0,1,2015.0,2042,3514,...,0.581104,['D RO MULTIDISCIPLINARY SCIENCES'],1,000358595900105,17,0 5 8,0,11,@ Article,1221
84,1,A1996VG59600012,17,3,133.0,1996.0,1,2015.0,2183,3514,...,0.621229,['D RO MULTIDISCIPLINARY SCIENCES'],1,000358595900105,17,0 5 8,0,11,@ Article,1221
85,1,000301376000017,2,0,35.0,2012.0,8,2012.0,762,2700,...,0.282222,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319
86,1,000073289300013,3,0,64.0,1998.0,8,2012.0,994,2700,...,0.368148,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",0,000312910200007,33,,0,3,@ Article,319
87,1,A1997XH86900011,4,0,194.0,1997.0,8,2012.0,996,2700,...,0.368889,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",0,000312910200007,33,,0,3,@ Article,319
88,1,000244396300011,5,0,104.0,2007.0,8,2012.0,1451,2700,...,0.537407,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",0,000312910200007,33,,0,3,@ Article,319
89,1,000300416100024,6,0,36.0,2012.0,8,2012.0,1453,2700,...,0.538148,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",0,000312910200007,33,,0,3,@ Article,319
90,1,000248638400022,8,0,47.0,2007.0,8,2012.0,1795,2700,...,0.664815,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",0,000312910200007,33,,0,3,@ Article,319
91,1,000279366300007,11,0,12.0,2010.0,8,2012.0,1798,2700,...,0.665926,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",0,000312910200007,33,,0,3,@ Article,319
92,1,000296953400004,12,0,13.0,2011.0,8,2012.0,1949,2700,...,0.721852,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319
93,2,000296953400004,12,3,13.0,2011.0,8,2012.0,1409,4296,...,0.327980,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",0,000312910200007,33,,0,3,@ Article,319
94,1,000285031700011,14,0,10.0,2010.0,8,2012.0,1966,2700,...,0.728148,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319
95,1,000264346900006,15,0,15.0,2009.0,8,2012.0,1977,2700,...,0.732222,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319
96,2,000264346900006,15,3,15.0,2009.0,8,2012.0,2668,4296,...,0.621043,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319
97,1,000265523300018,16,1,31.0,2009.0,8,2012.0,502,4727,...,0.106198,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319
98,1,000231855500001,17,1,41.0,2005.0,8,2012.0,1521,4727,...,0.321769,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319
99,1,000183832900044,19,1,3089.0,2003.0,8,2012.0,4055,4727,...,0.857838,"['D YU TROPICAL MEDICINE', 'D TI PARASITOLOGY']",1,000312910200007,33,,0,3,@ Article,319

In [5]:
len(plos_df_simple), len(list_expertise_papers), len(dict_plos_UT_list_papers_authored_by_team)

(156558, 156558, 158813)

In [7]:
cont  =1
for key in dict_plos_UT_list_papers_authored_by_team:
    if len(dict_plos_UT_list_papers_authored_by_team[key]) == 0:
        cont +=1
print (cont)

2475

In [8]:
len(dict_plos_UT_list_papers_authored_by_team)

158813

In [ ]:


########### I load all aux. dictionaries that i need for this third part of the code:
try:

    dict_DAIS_list_papers = pickle.load(open('../data/dict_DAIS_list_papers.pkl', 'rb'))   
    print ("done loading  ../data/dict_DAIS_list_papers.pkl") 
except:        
    print ("MISSING FILE!  ../data/dict_DAIS_list_papers.pkl           FORCED EXIT.")
    exit()





try:
    tot_list_DAIS = pickle.load(open('../data/tot_list_DAIS.pkl', 'rb'))   
    print ("done loading  ../data/tot_list_DAIS.pkl")    ###   697,993   authors (of all the plos papers)

    dict_plos_paper_UT_list_DAIS = pickle.load(open('../data/dict_plos_paper_UT_list_DAIS.pkl', 'rb'))            
    print ("done loading  ../data/dict_plos_paper_UT_list_DAIS.pkl")   # 158,813   plos papers
except:
    print ("MISSING FILE!  ../data/dict_plos_paper_UT_list_DAIS.pkl           FORCED EXIT.")
    exit()








try:
    dict_all_papers_authored_publ_year = pickle.load(open('../data/dict_all_papers_authored_publ_year.pkl', 'rb'))  
    print ("done loading ../data/dict_all_papers_authored_publ_year.pkl" )   # around 12M of keys
except:
    print ("MISSING FILE!  ../data/dict_all_papers_authored_publ_year.pkl           FORCED EXIT.")
    exit()







list_paper_UT = pickle.load(open('../data/list_paper_UT.pkl', 'rb'))
print ("done loading pickle list_paper_UT")







try:
    dict_UT_plos_paper_publication_year = pickle.load(open('../data/dict_UT_plos_paper_publication_year.pkl', 'rb'))  
    print ("done loading ../data/dict_UT_plos_paper_publication_year.pkl" )   # around 12M of keys
except:
    print ("MISSING FILE!  ../data/dict_UT_plos_paper_publication_year.pkl           FORCED EXIT.")
    exit()






try:
    dict_all_authored_paper_UT_list_UT_references = pickle.load(open('../data/master_dict_all_authored_paper_UT_list_UT_references.pkl', 'rb'))  
    print ("done loading ../data/master_dict_all_authored_paper_UT_list_UT_references.pkl" )   # around 12M of keys
except:
    print ("MISSING FILE!  ../data/master_dict_all_authored_paper_UT_list_UT_references.pkl           FORCED EXIT.")
    exit()

In [ ]:
len(dict_UT_plos_paper_publication_year), len(dict_all_papers_authored_publ_year)

# len(list(set(dict_UT_plos_paper_publication_year) & set(dict_all_papers_authored_publ_year)))   #  157967

In [ ]:





###############################################################
#####################   now i finally get the actual number of references used previously by all team members of a given paper, as well as all the papers (expertise) they have individually written


print ("\nworking on getting  dict_plos_UT_list_references_used_prior     and     dict_plos_UT_list_papers_authored_by_team   .................. (N_tot = 158K)")

dict_plos_UT_list_references_used_prior={}
dict_plos_UT_list_papers_authored_by_team={}

list_not_found_authored_papers=[]


cont  = 1
for paper_UT in list_paper_UT:   #### loop over all plos papers:  # tot 158K  


    if cont % 10000 == 0:

        with open('../data/dict_plos_UT_list_references_used_prior_partial.pkl', 'wb') as handle:
             pickle.dump(dict_plos_UT_list_references_used_prior, handle, protocol = 2)
        print ("written:",'../data/dict_plos_UT_list_references_used_prior_partial.pkl',len(dict_plos_UT_list_references_used_prior))   




        with open('../data/dict_plos_UT_list_papers_authored_by_team_until_then_partial.pkl', 'wb') as handle:
             pickle.dump(dict_plos_UT_list_papers_authored_by_team, handle, protocol = 2)
        print ("written:",'../data/dict_plos_UT_list_papers_authored_by_team_until_then_partial.pkl',len(dict_plos_UT_list_papers_authored_by_team))   

        print (cont)




    plos_year = dict_UT_plos_paper_publication_year[paper_UT]

    dict_plos_UT_list_papers_authored_by_team[paper_UT] = []  # until the publication  date of the PLOS paper that is    

    list_references_prior = []
  
    lista_DAIS = dict_plos_paper_UT_list_DAIS[paper_UT]

    for DAIS in lista_DAIS:   ########### loop over authors of the focus PLOS paper 
        list_authored_papers_by_DAIS = dict_DAIS_list_papers[DAIS]

        for authored_paper in list_authored_papers_by_DAIS:  ############## loop over all papers authored by all authors of the focus PLOS paper

                try:
                    authored_paper_year = dict_all_papers_authored_publ_year[authored_paper]

                    if authored_paper_year < plos_year : # it only counts towards the team's expertise if it was published before the focus plos paper                        
                        list_references_prior += dict_all_authored_paper_UT_list_UT_references[authored_paper]
                        dict_plos_UT_list_papers_authored_by_team[paper_UT].append(authored_paper)
                except KeyError: #pass
                    list_not_found_authored_papers.append(authored_paper)



        #### i remove duplicated ref:        
        dict_plos_UT_list_references_used_prior[paper_UT] = list(set(list_references_prior))
        dict_plos_UT_list_papers_authored_by_team[paper_UT] = list(set(dict_plos_UT_list_papers_authored_by_team[paper_UT]))
        

    cont +=1





with open('../data/dict_plos_UT_list_references_used_prior.pkl', 'wb') as handle:
             pickle.dump(dict_plos_UT_list_references_used_prior, handle, protocol = 2)
print ("written:",'../data/dict_plos_UT_list_references_used_prior.pkl',len(dict_plos_UT_list_references_used_prior))   




with open('../data/dict_plos_UT_list_papers_authored_by_team.pkl', 'wb') as handle:
             pickle.dump(dict_plos_UT_list_papers_authored_by_team, handle, protocol = 2)
print ("written:",'../data/dict_plos_UT_list_papers_authored_by_team.pkl',len(dict_plos_UT_list_papers_authored_by_team))   




list_not_found_authored_papers =  list(set(list_not_found_authored_papers))




print ("# authored papers not found:",len(list_not_found_authored_papers ))

In [ ]:


# path = '../data/dict_plos_UT_list_papers_authored_by_team_until_then_*'   
# lista_files=sorted(glob.glob(path))
# lista_files

In [ ]:
path = '../data/dict_plos_UT_list_references_used_prior_*'   
lista_files=sorted(glob.glob(path))
lista_files

In [ ]:
#####  dict_plos_UT_list_papers_authored_by_team*

# path = '../data/dict_plos_UT_list_papers_authored_by_team_until_then_*'   
# lista_files=sorted(glob.glob(path))

# master_dict  = {}
# lista_all_authored_UTs=[]

# for filename in lista_files:
#     dict_plos_UT_list_papers_authored_by_team = pickle.load(open(filename, 'rb'))
#     lista_all_authored_UTs += list(dict_plos_UT_list_papers_authored_by_team.keys())
#     print ("done loading", filename, len(dict_plos_UT_list_papers_authored_by_team), len(lista_all_authored_UTs))

#     master_dict.update(dict_plos_UT_list_papers_authored_by_team)
# with open('../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl', 'wb') as handle:
#              pickle.dump(master_dict, handle, protocol = 2)
# print ("written:",'../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl',len(master_dict))   











###### dict_plos_UT_list_references_used_prior*

path = '../data/dict_plos_UT_list_references_used_prior_*'   
lista_files=sorted(glob.glob(path))

master_dict  = {}
lista_all_authored_UTs=[]




# lista_keys1=[]
# for filename in lista_files[:8]:  #[0:8]   and [8:]
#     dict_plos_UT_list_references_used_prior = pickle.load(open(filename, 'rb'))
#     lista_all_authored_UTs += list(dict_plos_UT_list_references_used_prior.keys())
#     print ("done loading", filename, len(dict_plos_UT_list_references_used_prior), len(lista_all_authored_UTs))

#     master_dict.update(dict_plos_UT_list_references_used_prior)


# with open('../data/master_dict_plos_UT_list_references_used_prior1.pkl', 'wb') as handle:
#              pickle.dump(master_dict, handle, protocol = 2)
# print ("written:",'../data/master_dict_plos_UT_list_references_used_prior1.pkl',len(master_dict))   





# lista_keys1 = list(master_dict.keys())
# print (len(lista_keys1))







lista_keys2=[]
for filename in lista_files[8:]:  #[0:8]   and [8:]
    dict_plos_UT_list_references_used_prior = pickle.load(open(filename, 'rb'))
    lista_all_authored_UTs += list(dict_plos_UT_list_references_used_prior.keys())
    print ("done loading", filename, len(dict_plos_UT_list_references_used_prior), len(lista_all_authored_UTs))

    master_dict.update(dict_plos_UT_list_references_used_prior)


with open('../data/master_dict_plos_UT_list_references_used_prior2.pkl', 'wb') as handle:
             pickle.dump(master_dict, handle, protocol = 2)
print ("written:",'../data/master_dict_plos_UT_list_references_used_prior2.pkl',len(master_dict))   





lista_keys2 = list(master_dict.keys())
print (len(lista_keys2))

In [ ]:
print (len(lista_keys2) + len(lista_keys1))

In [ ]:
lista_keys1

In [ ]:
lista_files[8:]

In [ ]:
lista_files

In [ ]:


    with open('../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl', 'wb') as handle:
                 pickle.dump(master_dict, handle, protocol = 2)
    print ("written:",'../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl',len(master_dict))   





with open('../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl', 'wb') as handle:
             pickle.dump(master_dict, handle, protocol = 2)
print ("written:",'../data/master_dict_plos_UT_list_papers_authored_by_team_until_then.pkl',len(master_dict))

In [ ]:
len(dict_plos_UT_list_papers_authored_by_team)